-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        rounding = 0,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@90.00Hz",
    position = "0x0",
    scale = 1.8,
    cm = "srgb",
})

-- Keybinds
hl.bind("SHIFT + CTRL + ESCAPE", hl.dsp.exec_cmd("kitty -e btop"))
hl.bind("SUPER + CTRL + V", hl.dsp.exec_cmd("~/.config/waybar/themes/custom1/vpn-waybar.sh menu"))
